<?php

use Drupal\Core\Form\FormStateInterface;

/**
* Implements hook_form_alter().
*/
function passwords_reset_redirect_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'user_form') {
    if (isset($_REQUEST['pass-reset-token'])) {
      array_unshift($form['#validate'], 'passwords_reset_redirect_validate');
    }
  }
}

/**
 * Custom submit form to redirect after password reset.
 */
function passwords_reset_redirect_validate(array &$form, FormStateInterface $form_state) {
  $redirect = \Drupal::config('passwords_reset_redirect.settings')->get('redirect_after_reset');
  if ($redirect) {
    $request = \Symfony\Component\HttpFoundation\Request::create($redirect);
    $router = \Drupal::service('router.no_access_checks');
    $match = [];
    try {
      $match = $router->matchRequest($request);
      $form_state->setRedirect($match['_route']);
    }
    catch (\Exception $e) {
      throw $e;
    }
  }
}
